//Add person
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Lucía Píriz",
    "number": "222-222-222"
}

###
//Error: Name and number required
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    
}

###
//Error: Number validation
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Manuel Sergei",
    "number": "1"
}